[package]
name = "generic_hash"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
hex = "0.4.3"
sha2 = "0.10.9"
hashcat-sys = { path = "../../hashcat-sys" }

[profile.release]
strip = "symbols"
